<?php

            return

            $tr = [
'str' => [
'0' => 'CENTRO DE SALUD ESPAÑOL: UNA FORMA INNOVADORA DE PERDER DE 5 A 7 KG POR SEMANA, SIN PASTILLAS, DIETA Y DEPORTE',
'1' => 'Actualizado',
'2' => 'INICIO',
'3' => 'POLÍTICA',
'4' => 'ECONOMÍA',
'5' => 'MUNDO',
'6' => 'EVENTOS',
'7' => 'DEPORTE',
'8' => 'CIENCIA',
'9' => 'CULTURA',
'10' => 'BÚSQUEDA',
'11' => 'Iniciar sesión',
'12' => 'Nos cuenta Alvaro Suarez, doctor en Medicina Cientifica',
'13' => '¿Qué es Idealica?',
'14' => 'Las propiedades principales de Idealica:',
'15' => 'Quema de la grasa',
'16' => 'Control del apetito',
'17' => 'Normalización de los niveles hormonales.',
'18' => 'Rejuvenecimiento y limpieza del organismo.',
'19' => 'Efecto energetico',
'20' => 'Resultados después de 48 días de tomar Idealica:',
'21' => 'Resultados después de 38 días de tomar Idealica:',
'22' => 'Resultados después de 45 días de tomar Idealica:',
'23' => 'Comentarios de especialistas:',
'24' => 'Un grupo de personas (100 personas) con sobrepeso tomó gotas de Idealica dos veces al día, por la mañana y por la noche antes de las comidas. El experimento duró un mes. Ninguno de los voluntarios cambió su dieta habitual. Durante el experimento, se obtuvieron los siguientes resultados:',
'25' => '1. Pérdida de peso de 12 a 15 kg.',
'26' => '2. Mejora significativa del metabolismo.',
'27' => '3. Incremento del tono muscular y actividad física.',
'28' => '4. Mejora de la función hepática y del sistema endocrino.',
'29' => 'Su nombre',
'30' => 'Nombre',
'31' => 'Su número de teléfono',
'32' => 'ORDENAR',
'33' => 'la oferta de 50% de descuento termina en:',
'34' => 'Precio original:',
'35' => 'Precio promocional:',
'36' => 'DISCUSIÓN',
'37' => 'COMENTARIOS POPULARES',
'38' => 'TODOS LOS COMENTARIOS',
'39' => 'Monica',
'40' => 'Alvaro Torres',
'41' => 'Sandra',
'42' => 'Ana',
'43' => 'Maria',
'44' => 'Alvaro Torres',
'45' => 'María del Carme',
'46' => 'Elena',
'47' => 'Vicenta',
'48' => 'Hugo',
'49' => 'Carla',
'50' => 'Sandra',
'51' => 'Esperanza',
'52' => 'Alvaro Torres',
'53' => 'Rocío',
'54' => 'Vanesa',
'55' => 'Francisca',
'56' => 'Alvaro Torres',
'57' => 'Margarita',
'58' => 'Milagros',
'59' => 'Alvaro Torres',
'60' => 'Pilar',
'61' => 'Alvaro Torres',
'62' => 'Antonia',
'63' => 'Alvaro Torres',
'64' => 'Emilia',
'65' => 'María Dolores',
'66' => 'Alvaro Torres',
'67' => 'Eva ',
'68' => 'Marta ',
'69' => 'Carmen',
'70' => 'Beatriz ',
'71' => 'Alvaro Torres',
'72' => 'Carla ',
'73' => 'Alvaro Torres',
'74' => '¡Chicos, esto realmente funciona!  Bajé 25 kg con la ayuda de las gotas, pero lo mejor es que me siento como una auténtica belleza, me gusta el hecho de que mi hermosa figura finalmente se hizo visible y que la barriga abultada haya desaparecido por completo.  Es un resultado fantástico, aunque ya he probado muchas cosas y nada me ha ayudado antes.',
'75' => 'Acabo de empezar a tomar Idealica, pero ya siento un aumento en la actividad, tengo grandes planes con estas gotas.  En un mes, les mostraré en qué me he convertido.',
'76' => 'Hola, he perdido 11 kg en 3 semanas usando este producto.  ¡Esta es mi victoria!  ¡Han pasado seis meses y mi peso sigue estable!',
'77' => 'También perdí peso gracias a estas gotas, logré quitar la grasa del abdomen y tonificar mi cuerpo.  Y en total perdi 18 kg.',
'78' => 'Antes de tomar Idealica, pesaba 90 kg.  Cuando era más joven, tenía un gran físico atlético, pero a medida que crecía comencé a acumular grasa en el estómago y los muslos.  ¡Me di cuenta de que necesitaba hacer algo ahora mismo!  Entrené durante casi un año, pero no logré el resultado deseado.  Al final, agregué estas gotas a mi dieta diaria, y después de un par de semanas, recuperé mi cuerpo atlético que hizo que las mujeres se volvieran locas.  Ha pasado un año y mis kilos de más no han vuelto, y estoy seguro de que no volverán.  ',
'79' => 'No sé de otros, pero Idealica me ayudó mucho, perdí 20 kg en dos meses y estoy muy orgullosa de mi resultado',
'80' => '¿Por qué no puedes controlar lo que comes?  ¡Come menos y pierde peso!  Sois mujeres adultas, ¡¿no podéis controlaros ?!',
'81' => '¡El doctor tiene razón!  Estoy constantemente a dieta, pero no ayuda en absoluto.  El peso se detiene y no desaparece, incluso si me muero de hambre todo el día ...',
'82' => '¿Por qué existen estándares?  ¿Por qué todo el mundo tiene que ser delgado?  Por ejemplo, peso 79 kg y mido 167 y no me avergüenzo de eso.  ¡Me encanta cómo me veo y me siento genial!',
'83' => 'Chicas, ámense a sí mismas a pesar del peso.  Todas las modelos y reinas de belleza en la vida cotidiana son mujeres comunes, con celulitis y sobrepeso.  Y en todas las fotos están retocadas =) bueno, tal vez alguien necesite esas gotas milagrosas, pero yo me siento cómoda ser gorda =)',
'84' => '¡AYUDA!  ¡NECESITO PERDER 9 KG!  ¡ESTUVE EN CASA DURANTE VARIOS MESES Y SUBÍ DE PESO!  ¡PERO NO PUEDO SENTARME EN UNA DIETA!  ¡NO TENGO EL PODER DE LA VOLUNTAD, CORRO INMEDIATAMENTE Y OBTENGO AÚN MÁS!  ¡SOY TAN PEREZOSA, PERO TAMBIÉN QUIERO PERDER PESO!',
'85' => 'Peso 97 kg y no sé cómo deshacerme del exceso de peso ... Me temo que pronto pesaré 100 kg.  ¿QUÉ TENGO QUE HACER?  ¿Dónde pedir estas maravillosas gotas?',
'86' => '¡Hola!  Soy madre de dos hijos y, por lo que recuerdo, estoy tratando de adelgazar todo el tiempo ... Las dietas no funcionan, porque solo aguanto un par de días y luego me derrumbo y empiezo a comer de todo.  No tengo tiempo para los deportes.  Leí sobre Idealica, su composición natural y segura, y me pregunté.  Dime cuánto tiempo debo tomar estas gotas para que se note el resultado.  ¡Gracias por adelantado!',
'87' => 'Tengo 50 años y tenía muchas ganas de perder peso.  A mi edad, es muy difícil bajar de peso, porque el metabolismo se ralentiza ... ¡Así que pedí el tratamiento de Idealica y perdí 19 kg!  ¡El efecto me asombró!  ¡19 kg en dos meses!  No esperaba tales resultados, así que estoy super feliz.  ¡Gracias por el artículo!  Recomiendo estas gotas a todo el mundo.',
'88' => 'Me alegro de haber encontrado este artículo.  Pensé que nunca estaría delgada en esta vida.  Empecé a tomar gotas hace una semana.  Hasta ahora he perdido tres kilogramos.  No he cambiado mi estilo de vida, tampoco he cambiado nada en nutrición, pero ahora como en cantidades más pequeñas.   Ya no tengo un apetito loco, ya no tengo ganas de comer bocadillos todo el tiempo.  No sé quién inventó este producto, pero estoy muy agradecida por eso.',
'89' => '¿Dónde puedo comprar este producto?  Las farmacias no venden Idealica, pero tengo muchas ganas de comprar.',
'90' => 'ORDENAR Idealica',
'91' => 'Para ponerse en contacto con el equipo editorial o notificar posibles errores, utilice el formulario de comentarios. © 2020 El recurso puede contener 18+ materiales',
'92' => 'Política de privacidad',
],
'block' => [
'b0' => [
'0' => 'La dieta, el ejercicio, las pastillas y la liposucción son las principales formas de combatir el sobrepeso en la actualidad.  Sin embargo, a juzgar por el hecho de que el número de personas obesas sigue aumentando, ninguno de estos métodos es realmente eficaz.  La situación cambió, cuando aparecieron en España',
'1' => 'gotas Idealica  ',
'2' => 'un producto que estimula la pérdida de peso natural.',
],
'b1' => [
'0' => 'Respondiendo sus preguntas',
'1' => 'Alvaro Torres',
'2' => 'Director del Centro Nacional de Ciencias Médicas, Doctor en Medicina, Especialista Honorario de España, nutricionista',
'3' => 'Experiencia laboral: 32 años',
],
'b2' => [
'0' => 'Si su organismo carece de vitamina A, coma naranjas, si le falta fósforo, coma pescado, si le falta vitamina C, coma tomates. Unicamente las gotas de Idealica contienen todos los oligoelementos necesarios que ayudan a quemar grasa en el cuerpo humano.',
'1' => 'Ademas es un súper antioxidante que quema grasas y normaliza la actividad de todo el organismo.',
],
'b3' => [
'0' => 'Idealica: concentrado vegetal.',
'1' => '25 gotas: ¡una porción contiene la cantidad necesaria de sustancias activas que aumentan la tasa de quema de grasa 10 veces!',
'2' => 'Está clínicamente probado que Idealica acelera el metabolismo, restaura la actividad del sistema endocrino, estimula la regeneración de tejidos y suprime el hambre.  El producto es absolutamente natural y es un estimulador activo de procesos naturales en el cuerpo humano.  Dado que la quema de grasa se produce a través de un metabolismo rápido, no se requiere dieta.  Una dieta equilibrada es suficiente para mantener un metabolismo adecuado.',
'3' => 'Además, no se necesita actividad física intensiva.',
'4' => 'Si lo desea, puede realizar ejercicios sencillos para aumentar el tono muscular.',
],
'b4' => [
'0' => 'Gracias a Idealica, el metabolismo se acelera significativamente y, por lo tanto, la grasa subcutánea en las áreas problemáticas ',
'1' => 'se quema a una velocidad de 700 gramos por día.',
'2' => 'Las gotas de Idealica también son efectivas en los casos en que las fluctuaciones hormonales son la causa del sobrepeso.',
'3' => 'Si tiene una tendencia natural al sobrepeso, ¡este producto es definitivamente para usted!',
],
'b5' => [
'0' => 'En España, este producto apareció recientemente, pero ya ha logrado establecerse como el producto favorito de los culturistas y atletas que necesitan ',
'1' => 'perder peso rápidamente y mantener un bajo porcentaje de grasa corporal.',
],
'b6' => [
'0' => 'Dr. Samuel Gómez',
'1' => 'nutricionista y endocrinólogo',
'2' => 'Experiencia laboral: 27 años',
],
'b7' => [
'0' => '“Lo más importante para perder peso es no empeorar la condición del organismo.  Desafortunadamente, las formas más populares de perder peso no pueden presumir de esto.  Es muy difícil seguir constantemente una dieta, no todo el mundo puede soportar la abstinencia prolongada de alimentos ricos en calorías.  Sin alcanzar el objetivo, las personas recurren a tomar pastillas nocivas u otros medicamentos para adelgazar, la mayoría de los cuales provocan graves trastornos en el organismo, desequilibrio hormonal y disminución de la inmunidad.',
'1' => 'La pérdida de peso debe ser natural y segura para la salud.',
'2' => 'Hoy, las gotas de ',
'3' => ' Idealica',
'4' => 'son el único remedio capaz de esto.  Los microelementos activos Idealica aceleran el metabolismo 10 veces y estimulan la quema de grasa intensiva.  Estoy convencido de que estas gotas son el mejor remedio de la dietética moderna.   Es un producto seguro  en el que puede confiar completamente.“',
],
'b8' => [
'0' => 'Dra. Elena Juárez ',
'1' => 'nutricionista y endocrinólogo',
'2' => 'Experiencia laboral: 18 años',
],
'b9' => [
'0' => '“Las mujeres vienen a mi consulta con lágrimas en los ojos después de haber probado todo y no han logrado ningún resultado, o el peso ha vuelto después de una dieta abandonada. Solía aconsejarles que se calmaran y comenzaran de nuevo. Pero hoy hay una mejor opción: ',
'1' => 'Idealica.',
'2' => 'Nunca ha sido tan fácil perder kilos de más. Gracias a Idealica, perderá hasta 10 kg al mes de una manera completamente natural. Es un producto totalmente natural, adecuado para todos, independientemente de su sexo, edad y peso.',
'3' => 'La pérdida de peso se logra mediante la quema de grasa, no debido a la deshidratación del cuerpo o la pérdida de masa muscular.',
'4' => 'Personalmente recomiendo este producto a todos mis pacientes, y todos me agradecen el hecho de que hayan podido lograr un cuerpo delgado“.',
],
'b10' => [
'0' => '¡Importante!  Está comprobado que el otoño es la mejor época para adelgazar y normalizar las hormonas.  Debido a los cambios en la temperatura promedio del aire y la aceleración del metabolismo, el efecto de uso de
',
'1' => 'Idealica ',
'2' => 'aumenta y la grasa se quema un 45% más rápido.',
],
'b11' => [
'0' => 'Investigación',
'1' => 'Resultados de la investigación de laboratorio sobre',
'2' => ' Idealica ',
'3' => 'en colaboración con la Asociación de Alimentación Saludable::',
],
'b12' => [
'0' => '1. Pérdida de peso de 12 a 15 kg.',
'1' => '- pérdida de 15 kg - 95%',
'2' => '- pérdida de 12 kg - 100%.',
'3' => '* La pérdida en este caso significa deshacerse de la grasa.',
'4' => '2. Mejora significativa del metabolismo.',
'5' => '3. Aumenta el tono muscular y la actividad física.',
'6' => '4. Mejora de la función hepática y del sistema endocrino.',
'7' => 'Se ha demostrado que Idealica tiene un fuerte efecto en la aceleración del metabolismo y la quema de grasa.',
'8' => 'Indicado para las personas con sobrepeso, personas con metabolismo alterado y diabetes.',
],
'b13' => [
'0' => '¡ATENCIÓN!  ¡En el territorio de España , Idealica',
'1' => ' se puede comprar solo en el ',
'2' => 'SITIO WEB OFICIAL del FABRICANTE!',
],
'b14' => [
'0' => '127 ',
'1' => 'usuarios dejaron ',
'2' => '203 ',
'3' => 'comentarios',
],
'b15' => [
'0' => 'Probaré ',
'1' => ' Idealica ',
'2' => 'y luego publicaré los resultados.  Voy a ir a la universidad este año y realmente quiero comenzar una nueva vida con una nueva figura delgada.  Siempre se burlaban de mí en la escuela por tener sobrepeso, y eso me enojaba.  ¡Perderé 10 kilogramos y me convertiré en una reina de belleza!  =))',
],
'b16' => [
'0' => 'Monica, lo principal es tomar las gotas según las instrucciones.  Debido a que el producto es muy potente y en lugar de 10 kg, puede perder repentinamente los 20 kg.',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b17' => [
'0' => 'También comencé a tomar',
'1' => ' Idealica, ',
'2' => 'después de 2 semanas perdí solo 7 kilogramos = (¿esto es normal? ¿O estoy haciendo algo mal?',
],
'b18' => [
'0' => 'María, lo más probable es que hayas leído las instrucciones incorrectamente: es importante tomar Idealica 2 veces al día, 25 gotas, y tus resultados mejorarán significativamente.
',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b19' => [
'0' => 'Solo bebí gotas y comí todo lo que amo.  Y, sin embargo, perdí 10 kg.  ¡Creo que ',
'1' => 'Idealica ',
'2' => 'para bajar de peso es la mejor opcion que he probado!  Y la mejor parte es que no necesitas hacer ejercicio en el gimnasio para tener tu cuerpo en perfecta forma.  No tengo ni el tiempo ni las ganas de hacer esto ... En fin, estas gotas son como un regalo del cielo para los perezosos, como yo!  ¡Lo recomiendo!  Aquí están mis resultados:',
],
'b20' => [
'0' => 'Las gotas de',
'1' => ' Idealica ',
'2' => 'se han convertido en una verdadera salvación para mí.  Hace varios años tuve un accidente después del cual no pude moverme durante 8 largos meses.  Mientras estaba acostada en la cama, ¡engordé 25 kg!  Poco a poco comencé a caminar, pero ni siquiera pensaba en deportes ... porque necesitaba una rehabilitación larga y la condición solo podía empeorar.  Recibí mi primer pedido de Idealica de un amigo que acababa de regresar de América.  ¡Comenzó a tomar gotas allí y perdió hasta 13 kg en un mes!  También comencé a tomarlas, pero para ser honesto, no creía en el éxito.  Los tomé de acuerdo con las instrucciones: 25 gotas dos veces al día.  Una semana después, sentí cambios, mi estómago comenzó a reducisrse y la digestión se volvió más activa.  El metabolismo ha mejorado significativamente.  En las primeras 2 semanas perdí 8.5 kg, ¡y después de otro mes perdí 23.5 kg!  ¡No cambié mi dieta y esta pérdida de peso fue muy agradable y relajante!  ¡Todavía estoy asombrada!  Gracias a mi amigo por traer esta innovación desde América, de lo contrario habría pesado 83 kg.',
],
'b21' => [
'0' => 'Desafortunadamente, Esperanza no es tan simple.  Algunas personas no pueden perder peso de forma natural simplemente reduciendo el consumo de alimentos.  Su tendencia genética a tener sobrepeso dificulta la pérdida de peso, incluso si la persona está a dieta o hace ejercicio. Si esto no te afecta, estás de suerte..  Pero te aseguro que no todo el mundo tiene tanta suerte.
',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b22' => [
'0' => 'Es extraño que mucha gente piense que solo los médicos y nutricionistas conocen ',
'1' => 'Idealica,',
'2' => ' ya hemos reemplazado toda la nutrición deportiva en nuestro gimnasio, la mayoría de nuestros entrenadores trabajan con este producto, todos están muy contentos, lo recomiendo.  Estas gotas me ayudaron a perder 15 kg hace seis meses.  Y ahora quiero repetir el tratamiento solo por prevención.  Es un concentrado vegetal natural y seguro.  Y todos mis amigos conocen estas gotas desde hace mucho tiempo, así que no es un secreto.',
],
'b23' => [
'0' => 'Francisca, en el siglo XXI, las tendencias modernas y la moda hacen que las chicas se vayan a los extremos y parezcan modelos, muchas veces estos extremos afectan su salud.  Así, se ha creado un producto que te permitirá adelgazar sin poner en peligro tu salud.
',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b24' => [
'0' => 'Milagros, la pereza no es la mejor cualidad, ¡pero tiene suerte!  Idealica es exactamente lo que necesitas.  ¡Con estas gotas, no necesitas seguir dieta ni hacer ejercicio!  Solo sigue las instrucciones.
',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b25' => [
'0' => '¿Es el sitio web oficial del fabricante ',
'1' => 'es el único lugar donde puede comprar gotas de Idealica originales?  ¿O se pueden comprar en cualquier tienda online?',
],
'b26' => [
'0' => 'Pilar, lamentablemente, sí.  Porque las farmacias comerciales hacen un gran margen de beneficio sobre el producto y su costo aumenta varias veces.  En el sitio web oficial del fabricante, puede comprar un producto original y seguro al precio más bajo, posiblemente incluso con un descuento.',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b27' => [
'0' => 'Tomé las gotas de',
'1' => ' Idealica ',
'2' => 'hace aproximadamente un año, tenia serios problemas de peso.  Y después de 2 meses de tomar, perdí alrededor de 20 kilogramos, pero lo más importante, los kilogramos perdidos no regresaron, bueno, tal vez 1-2 kilogramos.',
],
'b28' => [
'0' => 'Antonia, mi consejo: para obtener los resultados a largo plazo, repite el tratamiento de Idealica.  Y, por supuesto, llevar una dieta equilibrada.',
'1' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b29' => [
'0' => 'Emilia, por supuesto, puede buscar estas gotas en otro lugar, pero personalmente ordené en  ',
'1' => 'el sitio web oficial del fabricante. ',
'2' => '¡Porque no quiero arriesgar mi salud!',
],
'b30' => [
'0' => 'Emilia, es importante no entrar en pánico, todo se puede solucionar.  Empieza de a poco.  Primero, desafortunadamente, estas gotas no se pueden encontrar en una farmacia. Ya he explicado por qué.  En segundo lugar, pida ',
'1' => 'Idealica ',
'2' => ' y siga las instrucciones.  Y todo saldrá bien.
',
'3' => 'Saludos cordiales,  Dr. Alvaro Torres',
],
'b31' => [
'0' => 'Para ser honesta, realmente no creía en tales remedios, pero después de 3 semanas de tomar Idealica tuve que comprarme ropa nueva porque todo era grande para mí.  Mis amigas piensan que me muero de hambre, que sigo una dieta estricta y que vivo en el gimnasio =) Todavía no he hablado de',
'1' => ' Idealica.
',
'2' => 'Estoy muy agradecida a los creadores de esta herramienta, porque comencé a sentirme mucho mejor.',
],
'b32' => [
'0' => 'Marta, no hay porque!  Es un gran honor y responsabilidad para nosotros ayudar a las personas, porque somos médicos y nos preocupamos por la salud de todos.',
'1' => 'Saludos cordiales, Dr. Alvaro Torres',
],
'b33' => [
'0' => 'Repito una vez más que las gotas de Idealica se pueden pedir SOLO en',
'1' => 'el sitio web oficial del fabricante.  ',
'2' => ' ¡Para no equivocarse, haga clic en el botón ORDENAR a continuación!  Especialmente para nuestros lectores, hay un gran descuento del fabricante.  Pero el descuento no durará mucho, ¡así que apúrate con tu pedido!  ¡Y por favor cuídese!',
'3' => 'Saludos cordiales, Dr. Alvaro Torres',
],
],
];
